import json
import shutil
from pathlib import Path

from app.agents.state import GraphState
from app.core.logging import get_logger

logger = get_logger(__name__)


def packager_node(state: GraphState) -> GraphState:
    """
    Plain code, not an LLM call. Writes a manifest of what succeeded/failed
    and zips the project directory for download. Always packages whatever
    exists -- a partially-failed project is still handed back to the user
    with a clear manifest, never silently discarded.
    """
    coder_state = state["coder_state"]
    project_root = Path(state["project_root"])
    plan = state["plan"]

    manifest = {
        "project_name": plan.name,
        "description": plan.description,
        "tech_stack": plan.tech_stack,
        "files_generated": sorted(coder_state.files_written.keys()),
        "files_failed": {path: reason for path, reason in coder_state.failed_files.items()
                          if path not in coder_state.files_written},
    }
    (project_root / "GENERATION_MANIFEST.json").write_text(
        json.dumps(manifest, indent=2, ensure_ascii=False),
        encoding="utf-8",
        errors="replace",
    )

    readme_path = project_root / "README.md"
    if not readme_path.exists():
        readme_path.write_text(
            f"# {plan.name}\n\n{plan.description}\n\n"
            f"## Tech stack\n" + "\n".join(f"- {t}" for t in plan.tech_stack) + "\n\n"
            f"## Features\n" + "\n".join(f"- {f}" for f in plan.features) + "\n\n"
            f"Generated by AI Coding Assistant. See GENERATION_MANIFEST.json for details.",
            encoding="utf-8",
            errors="replace",
        )

    archive_base = str(project_root.parent / f"{project_root.name}")

    zip_path = shutil.make_archive(archive_base, "zip", root_dir=project_root)
    logger.info("Packaged project at %s", zip_path)

    final_status = "done" if not manifest["files_failed"] else "done"  # partial success still "done"
    return {**state, "status": final_status}
